### ISSUE TITLE
Ejercicios faltantes

### ISSUE THREAD

**Issue by jcamilosarmientor** [jcamilosarmientor/RecursividadPhyton#1]
Creo que había un ejercicio sobre sacar la media de varios números, me confirman?

**Comment by cbdavide** [comment]
Yo me acuerdo que anote todos los ejercicios, y no tengo nada sobre eso.

**Comment by jcamilosarmientor** [comment]
Yo tengo estos:
- [x] Calcular el valor absoluto
- [x] Calcular el factorial de un número
- [x] Calcular el i-esimo término de la serie fibonacci
- [x] Calcular la potencia de n a la m
- [x] Multiplicar sumando
- [x] Dividir restando
- [x] Determinar si una cadena es palíndromo 
- [x] Sumatoria de los dígitos de un número 
- [ ] Convertir de base 2 a base 10 y de base 10 a base 2

**Comment by cbdavide** [comment]
Si, esos son, yo en la noche subo el de los cambios de base.

**Comment by jcamilosarmientor** [comment]
Creo que todos los ejercicios ya están completos, voy a revisarlos.
